server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: 75591734
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true